### PR TITLE
Impossible usage of `rust-scrypt` on Windows OS due to mmap call

### PR DESCRIPTION
**Pull request by r8d8**
`mmap` call used in Scrypt C library is only Unix specific.
Added conditional dependency for using `rust-crypto` on Windows
Related to #138

### CODE REVIEW

**Comment by dulanov** [comment]
did you remember to put a flag also in `cargo.toml`?

**Comment by dulanov** [comment]
```
cargo test --verbose %cargoflags%
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: manifest path `C:\projects\emerald-rs\Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
Command exited with code 101
```

**Comment by dulanov** [comment]
I also want to fix `.travis.yml` to fix it.

**Comment by r8d8** [comment]
.travis.yml or appveyor?
We using rust-crypto for `pbkdf2` on both Linux/Mac & Windows
so they required both, no need for Cargo tweak

**Comment by dulanov** [comment]
you right, probably in future we should switch to `ring`

**Pull request merged**
