### PR TITLE
Lack of functionality for storage switch

### PR DESCRIPTION
**Pull request by r8d8**
Added.
Migrate docs to markdown.

### CODE REVIEW

**Comment by splix** [comment]
Wondering, why Markdown?

**Comment by r8d8** [comment]
Crates.io added feature to render README files, and they only support markdown

**Comment by splix** [comment]
Ah, I see. Found these discussions md vs adoc for Rust docs

**Comment by r8d8** [comment]
@splix  can you approve once again, so I can merge it

**Pull request merged**
