### PR TITLE
Use io.add_method instead of io.add_async_method

### PR DESCRIPTION
**Pull request by sorpaas**
We don't currently use any futures feature. Async thus doesn't provide us any performance benefits. This allows us to use Rust's try macro and question mark syntax.

### CODE REVIEW

**Comment by dulanov** [comment]
Methods `emerald_newAccount` & `emerald_signTransaction` can be performed up to several seconds, it is not critical now, but better to execute them asynchronously.

**Comment by dulanov** [comment]
@sorpaas run `cargo install rustfmt --force --vers 0.8.4 && cargo fmt` to reformat all source code.

**Comment by sorpaas** [comment]
Ops, sorry!

**Comment by sorpaas** [comment]
I'm going to check whether we can take advantage of `futures` in `signTransactions`. If that works, I'm going to revert back to `io.add_async_method`. But it's more likely that it might just require using a full thread to run `signTransaction`. In the later case, using `add_method` and `add_async_method` would still be indifferent in terms of performance.

**Comment by r8d8** [comment]
Due to slow scrytp in rust crypto, sign transaction wouldn't benefit from a separate thread to much, I think so.

**Comment by sorpaas** [comment]
@r8d8 @dulanov If I understand it correctly, how the `jsonrpc_http` works (https://paritytech.github.io/jsonrpc/src/jsonrpc_http_server/lib.rs.html#296) is that it will use hyper to initialize several event loop / handling threads. Those are physical threads so they run concurrently. The default number of the threads are dependent on the number of CPUs available on the machine.

After that, when it receives a request, it will call the handler. If the handler is sync, it can only wait until the response is available. At that time, this event loop (while there might be other event loops available) will not be handling any other requests. The handler can also be async. In this case, the returned future will be jointly waited, and any time any of the future is finished, that response will be returned.

Currently, the function that `emerald_newAccount` use is `KeyFile::new`. Right now even if we implement it as async, what happens under the hood is as this:

- The event loop receives the response, call the handler. `KeyFile::new` is not async, so this event loop can do nothing else but wait a few seconds until it is finished.
- After that, it returns a future, but this future is immediately finished. So a response is returned.

You see that there's no difference currently than implementing it sync.

---

If we want to take advantage of async handlers, the correct way is:

- Create a wrapper around `KeyFile::new`. This wrapper creates a new thread and immediately returns a future.
- When the thread is finished, it marks that future as finished.

However, this requires some work. So what I suggest is:

- We implement all handlers as sync now, including `emerald_newAccount`, etc.
- We keep those "fast finished` handlers sync. This includes `emerald_version`, `emerald_heatbeat`, etc.
- Gradually, we add future support to the underlying library (`KeyFile::new`, etc.). After that, we change those `slow finished` handlers to async one by one.

**Comment by dulanov** [comment]
@sorpaas Yes, you right, firstly we should implemented it in fully synchronize way and improve it in the future.

**Pull request merged**
